# Generated by Django 4.2 on 2026-04-08 07:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Area or locality name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='District name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Districts',
                'db_table': 'district',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title/name', max_length=200)),
                ('description', models.TextField(help_text='Detailed property description', max_length=2000)),
                ('rent', models.PositiveIntegerField(help_text='Monthly rent amount (must be > 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.TextField(help_text='Complete address of the property', max_length=500)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude (-90 to 90)', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, help_text='Longitude (-180 to 180)', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('featured_image', models.ImageField(help_text='Main property image', upload_to='properties/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Area/locality where property is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='Room.area')),
                ('district', models.ForeignKey(help_text='District where property is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='Room.district')),
                ('landlord', models.ForeignKey(help_text='Landlord who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'property',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='State or region name', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'States',
                'db_table': 'state',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, help_text='Search query text', max_length=300)),
                ('min_rent', models.PositiveIntegerField(blank=True, help_text='Minimum rent filter', null=True)),
                ('max_rent', models.PositiveIntegerField(blank=True, help_text='Maximum rent filter', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('area', models.ForeignKey(blank=True, help_text='Area searched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to='Room.area')),
                ('district', models.ForeignKey(blank=True, help_text='District searched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to='Room.district')),
                ('state', models.ForeignKey(blank=True, help_text='State searched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to='Room.state')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the search', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
                ('viewed_property', models.ForeignKey(blank=True, help_text='Property viewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views_history', to='Room.property')),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'db_table': 'usersearchhistory',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], default='tenant', help_text='User role: tenant or landlord', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='10-digit phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be 10 digits')])),
                ('address', models.TextField(blank=True, help_text='User address', max_length=300, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pics/')),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'db_table': 'userprofile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Image title (e.g., "Bedroom", "Kitchen")', max_length=100)),
                ('image', models.ImageField(help_text='Property image', upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Room.property')),
            ],
            options={
                'verbose_name_plural': 'Property Images',
                'db_table': 'propertyimage',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(help_text='State where property is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='Room.state'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(help_text='State this district belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Room.state'),
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(help_text='District this area belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Room.district'),
        ),
        migrations.AddIndex(
            model_name='usersearchhistory',
            index=models.Index(fields=['user', '-timestamp'], name='usersearchh_user_id_af5ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='usersearchhistory',
            index=models.Index(fields=['district'], name='usersearchh_distric_95edc7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='userprofile_user_id_27d021_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='userprofile_role_0241ed_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property'], name='propertyima_propert_a11a54_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord'], name='property_landlor_0a6ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='property_status_b6c25e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district'], name='property_distric_3e3b37_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='property_created_ded475_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['state'], name='district_state_i_84d3bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['district'], name='area_distric_28f319_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('district', 'name')},
        ),
    ]
